/*FULL GRAMMAR SPEC:
<message>    ::= [':' <prefix> <SPACE> ] <command> <params> <crlf>
<prefix>     ::= <servername> | <nick> [ '!' <user> ] [ '@' <host> ]
<command>    ::= <letter> { <letter> } | <number> <number> <number>
<SPACE>      ::= ' ' { ' ' }
<params>     ::= <SPACE> [ ':' <trailing> | <middle> <params> ]
<middle>     ::= <Any *non-empty* sequence of octets not including SPACE or NUL or CR or LF, the first of which may not be ':'>
<trailing>   ::= <Any, possibly *empty*, sequence of octets not including NUL or CR or LF>
<crlf>       ::= CR LF

<target>     ::=  <to> [ "," <target> ]
<to>         ::= <channel> | <user> '@' <servername> | <nick> | <mask>
<channel>    ::= ('#' | '&') <chstring>
<servername> ::= <host>
<host>       ::= see RFC 952 [DNS:4] for details on allowed hostnames
<nick>       ::= <letter> { <letter> | <number> | <special> }
<mask>       ::= ('#' | '$') <chstring>
<chstring>   ::= <any 8bit code except SPACE, BELL, NUL, CR, LF and comma (',')>
<user>       ::= <nonwhite> { <nonwhite> }
<letter>     ::= 'a' ... 'z' | 'A' ... 'Z'
<number>     ::= '0' ... '9'
<special>    ::= '-' | '[' | ']' | '\' | '`' | '^' | '{' | '}'
<nonwhite>   ::= <any 8bit code except SPACE (0x20), NUL (0x0), CR (0xd), and LF (0xa)>
*/

#include <stdlib.h>

#define MAX_MESSAGELEN 513

#define CR 0x0D
#define LF 0x0A
#define SPACE 0x20
#define NUL 0x0
#define COLON 0x3B

enum {
    CMD_PASS,
    CMD_NICK,
    CMD_USER,
    CMD_SERVER,
    CMD_OPER,
    CMD_QUIT,
    CMD_SQUIT,
    CMD_JOIN,
    CMD_PART,
    CMD_MODE,
    CMD_TOPIC,
    CMD_NAMES,
    CMD_LIST,
    CMD_INVITE,
    CMD_KICK,
    CMD_VERSION,
    CMD_STATS,
    CMD_LINKS,
    CMD_TIME,
    CMD_CONNECT,
    CMD_TRACE,
    CMD_ADMIN,
    CMD_INFO,
    CMD_PRIVMSG,
    CMD_NOTICE,
    CMD_WHO,
    CMD_WHOIS,
    CMD_WHOWAS,
    CMD_KILL,
    CMD_PING,
    CMD_PONG,
    CMD_ERROR,
    CMD_AWAY,
    CMD_REHASH,
    CMD_RESTART,
    CMD_SUMMON,
    CMD_USERS,
    CMD_WALLOPS,
    CMD_USERHOST,
    CMD_ISON,
} command_id;

enum {
    ERR_NOSUCHNICK,
    ERR_NOSUCHSERVER,
    ERR_NOSUCHCHANNEL,
    ERR_CANNOTSENDTOCHAN,
    ERR_TOOMANYCHANNELS,
    ERR_WASNOSUCHNICK,
    ERR_TOOMANYTARGETS,
    ERR_NOORIGIN,
    ERR_NORECIPIENT,
    ERR_NOTEXTTOSEND,
    ERR_NOTOPLEVEL,
    ERR_WILDTOPLEVEL,
    ERR_UNKNOWNCOMMAND,
    ERR_NOMOTD,
    ERR_NOADMININFO,
    ERR_FILEERROR,
    ERR_NONICKNAMEGIVEN,
    ERR_ERRONEUSNICKNAME,
    ERR_NICKNAMEINUSE,
    ERR_NICKCOLLISION,
    ERR_USERNOTINCHANNEL,
    ERR_NOTONCHANNEL,
    ERR_USERONCHANNEL,
    ERR_NOLOGIN,
    ERR_SUMMONDISABLED,
    ERR_USERSDISABLED,
    ERR_NOTREGISTERED,
    ERR_NEEDMOREPARAMS,
    ERR_ALREADYREGISTERED,
    ERR_NOPERMFORHOST,
    ERR_PASSWDMISMATCH,
    ERR_YOUREBANNEDCREEP,
    ERR_KEYSET,
    ERR_CHANNELISFULL,
    ERR_UNKNOWNMODE,
    ERR_INVITEONLYCHAN,
    ERR_BANNEDFROMCHAN,
    ERR_BADCHANNELKEY,
    ERR_NOPRIVILEGES,
    ERR_CHANOPRIVSNEEDED,
    ERR_CANTKILLSERVER,
    ERR_NOOPERHOST,
    ERR_UMODEUNKNOWNFLAG,
    ERR_USERSDONTMATCH,

    RPL_NONE = 44,
    RPL_USERHOST,
    RPL_ISON,
    RPL_AWAY,
    RPL_UNAWAY,
    RPL_NOWAWAY,
    RPL_WHOISUSER,
    RPL_WHOISSERVER,
    RPL_WHOISOPERATOR,
    RPL_WHOISIDLE,
    RPL_ENDOFWHOIS,
    RPL_WHOISCHANNELS,
    RPL_WHOWASUSER,
    RPL_ENDOFWHOWAS,
    RPL_LISTSTART,
    RPL_LIST,
    RPL_LISTEND,
    RPL_CHANNELMODEIS,
    RPL_NOTOPIC,
    RPL_TOPIC,
    RPL_INVITING,
    RPL_SUMMONING,
    RPL_VERSION,
    RPL_WHOREPLY,
    RPL_ENDOFWHO,
    RPL_NAMEREPLY,
    RPL_ENDOFNAMES,
    RPL_LINKS,
    RPL_ENDOFLINKS,
    RPL_BANLIST,
    RPL_ENDOFBANLIST,
    RPL_INFO,
    RPL_ENDOFINFO,
    RPL_MOTDSTART,
    RPL_MOTD,
    RPL_ENDOFMOTD,
    RPL_YOUREOPER,
    RPL_REHASHING,
    RPL_TIME,
    RPL_USERSSTART,
    RPL_USERS,
    RPL_ENDOFUSERS,
    RPL_NOUSERS,
    RPL_TRACELINK,
    RPL_TRACECONNECTING,
    RPL_TRACEHANDSHAKE,
    RPL_TRACEUNKNOWN,
    RPL_TRACEOPERATOR,
    RPL_TRACEUSER,
    RPL_TRACESERVER,
    RPL_TRACENEWTYPE,
    RPL_TRACELOG,
    RPL_STATSLINKINFO,
    RPL_STATSCOMMANDS,
    RPL_STATSCLINE,
    RPL_STATSNLINE,
    RPL_STATSILINE,
    RPL_STATSKLINE,
    RPL_STATSYLINE,
    RPL_ENDOFSTATS,
    RPL_STATSLLINE,
    RPL_STATSUPTIME,
    RPL_STATSOLINE,
    RPL_STATSHLINE,
    RPL_UMODEIS,
    RPL_LUSERCLIENT,
    RPL_LUSEROP,
    RPL_LUSERUNKNOWN,
    RPL_LUSERME,
    RPL_ADMINME,
    RPL_ADMINLOC1,
    RPL_ADMINLOC2,
    RPL_ADMINEMAIL,
} reply_id;

static const char *commandArray[] = {
    "PASS",
    "NICK",
    "USER",
    "SERVER",
    "OPER",
    "QUIT",
    "SQUIT",
    "JOIN",
    "PART",
    "MODE",
    "TOPIC",
    "NAMES",
    "LIST",
    "INVITE",
    "KICK",
    "VERSION",
    "STATS",
    "LINKS",
    "TIME",
    "CONNECT",
    "TRACE",
    "ADMIN",
    "INFO",
    "PRIVMSG",
    "NOTICE",
    "WHO",
    "WHOIS",
    "WHOWAS",
    "KILL",
    "PING",
    "PONG",
    "ERROR",
    "AWAY",
    "REHASH",
    "RESTART",
    "SUMMON",
    "USERS",
    "WALLOPS",
    "USERHOST",
    "ISON",
};

static const char *replyArray[] = {
    "401",
    "402",
    "403",
    "404",
    "405",
    "406",
    "407",
    "409",
    "411",
    "412",
    "413",
    "414",
    "412",
    "422",
    "423",
    "424",
    "431",
    "432",
    "433",
    "436",
    "441",
    "442",
    "443",
    "444",
    "445",
    "446",
    "451",
    "461",
    "462",
    "463",
    "464",
    "465",
    "467",
    "471",
    "472",
    "473",
    "474",
    "475",
    "481",
    "482",
    "483",
    "491",
    "501",
    "502",
    "300",
    "302",
    "303",
    "301",
    "305",
    "306",
    "311",
    "312",
    "313",
    "317",
    "318",
    "319",
    "314",
    "369",
    "321",
    "322",
    "323",
    "324",
    "331",
    "332",
    "341",
    "342",
    "351",
    "352",
    "315",
    "353",
    "366",
    "364",
    "365",
    "367",
    "368",
    "371",
    "374",
    "375",
    "372",
    "376",
    "381",
    "382",
    "391",
    "392",
    "393",
    "394",
    "395",
    "200",
    "201",
    "202",
    "203",
    "204",
    "205",
    "206",
    "208",
    "261",
    "211",
    "212",
    "213",
    "214",
    "215",
    "216",
    "218",
    "219",
    "241",
    "242",
    "243",
    "244",
    "221",
    "251",
    "252",
    "253",
    "254",
    "255",
    "256",
    "257",
    "258",
    "259",
};
